export const defaultTheme = {
  colors: {
    white: "#FFFFFF",
    blue: "#0F52BA",
    black: "#000000",
    "gray-400": "#373737",
    "gray-800": "#2C2C2C",
  },
  textSizes: {
    "logo-l": "4rem",
    "title-xl": "4.8rem",
    "title-l": "3.2rem",
    "title-m": "2.4rem",
    "title-s": "2rem",
    "title-xs": "1.8rem",
    "text-l": "2rem",
    "text-m": "1.6rem",
    "text-s": "1.4rem",
    "text-xs": "1rem",
    "text-bold-xs": "1.2rem",
    "tag-bold": "1rem",
    "button-bold-g": "1.4rem",
    "button-regular-m": "1.4rem",
  },
  breakpoints: {
    XS: 0,
    SM: "576px",
    MD: "768px",
    LG: "992px",
    XL: "1200px",
  },
  fonts: {
    default: "var(--font-monteserrat)",
  },
};
